### ISSUE TITLE
Cannot start pyadselfservice

### ISSUE THREAD

**Issue by k1m0n3** [kanayak123/pyadselfservice#6]
Hello,

I got this error while running the project : 

[Fri Apr 06 12:54:56.383568 2018] [wsgi:error] [pid 3586:tid 140589328733952] [client 172.31.15.104:50468]     configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
[Fri Apr 06 12:54:56.383573 2018] [wsgi:error] [pid 3586:tid 140589328733952] [client 172.31.15.104:50468]   File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 53, in __getattr__
[Fri Apr 06 12:54:56.383582 2018] [wsgi:error] [pid 3586:tid 140589328733952] [client 172.31.15.104:50468]     self._setup(name)
[Fri Apr 06 12:54:56.383587 2018] [wsgi:error] [pid 3586:tid 140589328733952] [client 172.31.15.104:50468]   File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 41, in _setup
[Fri Apr 06 12:54:56.383594 2018] [wsgi:error] [pid 3586:tid 140589328733952] [client 172.31.15.104:50468]     self._wrapped = Settings(settings_module)
[Fri Apr 06 12:54:56.383609 2018] [wsgi:error] [pid 3586:tid 140589328733952] [client 172.31.15.104:50468]   File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 97, in __init__
[Fri Apr 06 12:54:56.383618 2018] [wsgi:error] [pid 3586:tid 140589328733952] [client 172.31.15.104:50468]     mod = importlib.import_module(self.SETTINGS_MODULE)
[Fri Apr 06 12:54:56.383623 2018] [wsgi:error] [pid 3586:tid 140589328733952] [client 172.31.15.104:50468]   File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
[Fri Apr 06 12:54:56.383631 2018] [wsgi:error] [pid 3586:tid 140589328733952] [client 172.31.15.104:50468]     __import__(name)
[Fri Apr 06 12:54:56.383645 2018] [wsgi:error] [pid 3586:tid 140589328733952] [client 172.31.15.104:50468] ImportError: No module named pyadselfservice.settings

any idea ?

**Comment by Gustavodecker** [comment]
Hello, did your setup work?
