### ISSUE TITLE
PASSWORD_MIN_ENTROPY

### ISSUE THREAD

**Issue by pchaploutskii** [kanayak123/pyadselfservice#9]
Hi,
do we know if this option PASSWORD_MIN_ENTROPY involved in code?

**Comment by kanayak123** [comment]
Yes, it's a config parameter for zxcvbn password checker.. if you don't want to enforce strong password, you can reduce it. Read the [zxcvbn password](https://pypi.org/project/django-zxcvbn-password/) checker guide.
